apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-controller-unifi
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/gero/kubernetes/controller-unifi"
