apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-controller-unifi
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
