apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
        - name: unifi-controller
          image: linuxserver/unifi-controller:latest
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 3478
              protocol: UDP
            - containerPort: 10001
              protocol: UDP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: unifi-volume
              mountPath: /config
      volumes:
        - name: unifi-volume
          persistentVolumeClaim:
            claimName: pvc-controller-unifi

---

apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-service-lb
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  loadBalancerIP: 10.12.0.201
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: udp-3478
      protocol: UDP
      port: 3478
      targetPort: 3478
    - name: udp-10001
      protocol: UDP
      port: 10001
      targetPort: 10001

