apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-homelab
  labels:
    app: homelab
    owner: gero
    name: pvc-homelab
spec:
  volumeName: pv-homelab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
